name: Publish Package to npmjs

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dist-tag:
        description: "npm dist-tag to publish under"
        required: false
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --immutable
      - run: yarn npm publish --access public --tag ${{ github.event.inputs.dist-tag || 'latest' }}
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
